/u/home/yaox/Matthias/drl_grasping
i6-gpu-1
Tue Sep 10 10:21:35 UTC 2024
Your system uses glibc newer than 2.31 which is used inside the container. Implementing --nv switch via a workaround. Let's hope it works!
[1;30mapptainer exec -B /lib/x86_64-linux-gnu/libcuda.so -B /lib/x86_64-linux-gnu/libcuda.so.1 -B /lib/x86_64-linux-gnu/libEGL_nvidia.so.0 -B /lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1 -B /lib/x86_64-linux-gnu/libGLESv1_CM.so.1 -B /lib/x86_64-linux-gnu/libGLESv1_CM.so -B /lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2 -B /lib/x86_64-linux-gnu/libGLESv2.so.2 -B /lib/x86_64-linux-gnu/libGLESv2.so -B /lib/x86_64-linux-gnu/libGLX_nvidia.so.0 -B /lib/x86_64-linux-gnu/libnvcuvid.so.1 -B /lib/x86_64-linux-gnu/libnvcuvid.so -B /lib/x86_64-linux-gnu/libnvidia-cfg.so -B /lib/x86_64-linux-gnu/libnvidia-cfg.so.1 -B /lib/x86_64-linux-gnu/libnvidia-compiler.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvidia-eglcore.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvidia-encode.so.1 -B /lib/x86_64-linux-gnu/libnvidia-encode.so -B /lib/x86_64-linux-gnu/libnvidia-fbc.so -B /lib/x86_64-linux-gnu/libnvidia-fbc.so.1 -B /lib/x86_64-linux-gnu/libnvidia-glcore.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvidia-glsi.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.530.41.03 -B /lib/libnvidia-gtk2.so.510.47.03 -B /lib/libnvidia-gtk3.so.510.47.03 -B /lib/x86_64-linux-gnu/libnvidia-ml.so -B /lib/x86_64-linux-gnu/libnvidia-ml.so.1 -B /lib/x86_64-linux-gnu/libnvidia-opencl.so.1 -B /lib/x86_64-linux-gnu/libnvidia-opticalflow.so -B /lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1 -B /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so -B /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1 -B /lib/x86_64-linux-gnu/libnvidia-rtcore.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvidia-tls.so.530.41.03 -B /lib/x86_64-linux-gnu/libnvoptix.so.1 -B /usr/share/glvnd/egl_vendor.d/10_nvidia.json --bind /etc/localtime:/etc/localtime:ro --bind /u/home/yaox/Matthias/drl_grasping_training_docker:/root/drl_grasping_training --bind /tmp/.ignition:/root/.ignition --bind /tmp/.pcg:/root/.pcg --bind /tmp/.ros:/root/.ros --bind /tmp/.rviz2:/root/.rviz2 --bind /tmp/.config/matplotlib:/root/.config/matplotlib --bind /tmp/.cache/matplotlib:/root/.cache/matplotlib --bind /u/home/yaox/Matthias/drl_grasping/visualizations:/root/visualizations --bind /u/home/yaox/Matthias/drl_grasping/scripts:/root/ws/src/drl_grasping/scripts --bind /u/home/yaox/Matthias/drl_grasping/launch:/root/ws/src/drl_grasping/launch --bind /u/home/yaox/Matthias/drl_grasping/examples:/root/ws/src/drl_grasping/examples --bind /u/home/yaox/Matthias/drl_grasping/hyperparams:/root/ws/src/drl_grasping/hyperparams --bind /u/home/yaox/Matthias/drl_grasping/rviz:/root/ws/src/drl_grasping/rviz --bind /u/home/yaox/Matthias/drl_grasping/drl_grasping:/root/ws/src/drl_grasping/drl_grasping /u/home/yaox/Matthias/drl_grasping_apptainer.sif ./.docker/apptainer_commands.bash[0m
INFO:    underlay of /usr/lib/libnvidia-gtk2.so.510.47.03 required more than 50 (65) bind mounts
INFO:    underlay of /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1 required more than 50 (1432) bind mounts
[1;30mros2 launch -a drl_grasping evaluate.launch.py seed:=77 robot_model:=lunalab_summit_xl_gen env:=GraspPlanetary-PointNet-Gazebo-v0 algo:=tqc log_folder:=/root/drl_grasping_training/train/GraspPlanetary-PointNet-Gazebo-v0/logs reward_log:=/root/drl_grasping_training/evaluate/GraspPlanetary-PointNet-Gazebo-v0 stochastic:=false n_episodes:=2 load_best:=false enable_rviz:=false no_render:=true log_level:=error load_checkpoint:=250000[0m
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-09-10-10-21-38-504562-i6-gpu-1-2998768
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [launch.user]: Bridge enabled between [ROS 2] /clock and [IGN] /world/drl_grasping_world/clock
[INFO] [launch.user]: Bridge enabled between [ROS 2] /tf and [IGN] /model/lunalab_summit_xl_gen/pose
[INFO] [launch.user]: Bridge enabled between [ROS 2] /lunalab_summit_xl_gen/cmd_vel and [IGN] /model/lunalab_summit_xl_gen/cmd_vel
[INFO] [launch.user]: Configuring drl_grasping for Ignition Gazebo world drl_grasping_world
	Robot model: lunalab_summit_xl_gen
	Prefix: robot_
[INFO] [robot_state_publisher-1]: process started with pid [2998780]
[INFO] [move_group-2]: process started with pid [2998782]
[INFO] [servo_node_main-3]: process started with pid [2998784]
[INFO] [spawner-4]: process started with pid [2998786]
[INFO] [spawner-5]: process started with pid [2998788]
[INFO] [spawner-6]: process started with pid [2998793]
[INFO] [static_transform_publisher-7]: process started with pid [2998802]
[INFO] [parameter_bridge-8]: process started with pid [2998805]
[INFO] [parameter_bridge-9]: process started with pid [2998807]
[INFO] [parameter_bridge-10]: process started with pid [2998818]
[INFO] [evaluate.py-11]: process started with pid [2998820]
[robot_state_publisher-1] Link robot_summit_xl_base_link had 5 children
[robot_state_publisher-1] Link robot_j2s7s300_link_base had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_1 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_2 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_3 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_4 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_5 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_6 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_7 had 4 children
[robot_state_publisher-1] Link robot_j2s7s300_end_effector had 0 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_1 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_tip_1 had 0 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_2 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_tip_2 had 0 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_3 had 1 children
[robot_state_publisher-1] Link robot_j2s7s300_link_finger_tip_3 had 0 children
[robot_state_publisher-1] Link robot_summit_xl_back_left_wheel had 0 children
[robot_state_publisher-1] Link robot_summit_xl_back_right_wheel had 0 children
[robot_state_publisher-1] Link robot_summit_xl_front_left_wheel had 0 children
[robot_state_publisher-1] Link robot_summit_xl_front_right_wheel had 0 children
[move_group-2] Link robot_summit_xl_base_link had 5 children
[move_group-2] Link robot_j2s7s300_link_base had 1 children
[move_group-2] Link robot_j2s7s300_link_1 had 1 children
[move_group-2] Link robot_j2s7s300_link_2 had 1 children
[move_group-2] Link robot_j2s7s300_link_3 had 1 children
[move_group-2] Link robot_j2s7s300_link_4 had 1 children
[move_group-2] Link robot_j2s7s300_link_5 had 1 children
[move_group-2] Link robot_j2s7s300_link_6 had 1 children
[move_group-2] Link robot_j2s7s300_link_7 had 4 children
[move_group-2] Link robot_j2s7s300_end_effector had 0 children
[move_group-2] Link robot_j2s7s300_link_finger_1 had 1 children
[move_group-2] Link robot_j2s7s300_link_finger_tip_1 had 0 children
[move_group-2] Link robot_j2s7s300_link_finger_2 had 1 children
[move_group-2] Link robot_j2s7s300_link_finger_tip_2 had 0 children
[move_group-2] Link robot_j2s7s300_link_finger_3 had 1 children
[move_group-2] Link robot_j2s7s300_link_finger_tip_3 had 0 children
[move_group-2] Link robot_summit_xl_back_left_wheel had 0 children
[move_group-2] Link robot_summit_xl_back_right_wheel had 0 children
[move_group-2] Link robot_summit_xl_front_left_wheel had 0 children
[move_group-2] Link robot_summit_xl_front_right_wheel had 0 children
[servo_node_main-3] Link robot_summit_xl_base_link had 5 children
[servo_node_main-3] Link robot_j2s7s300_link_base had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_1 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_2 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_3 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_4 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_5 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_6 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_7 had 4 children
[servo_node_main-3] Link robot_j2s7s300_end_effector had 0 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_1 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_tip_1 had 0 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_2 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_tip_2 had 0 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_3 had 1 children
[servo_node_main-3] Link robot_j2s7s300_link_finger_tip_3 had 0 children
[servo_node_main-3] Link robot_summit_xl_back_left_wheel had 0 children
[servo_node_main-3] Link robot_summit_xl_back_right_wheel had 0 children
[servo_node_main-3] Link robot_summit_xl_front_left_wheel had 0 children
[servo_node_main-3] Link robot_summit_xl_front_right_wheel had 0 children
[move_group-2] [ERROR] [1725963701.792403995] [moveit.ros.occupancy_map_monitor.middleware_handle]: No 3D sensor plugin(s) defined for octomap updates
[move_group-2] [96mLoading 'move_group/ApplyPlanningSceneService'...
[move_group-2] [0m[96mLoading 'move_group/ClearOctomapService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupCartesianPathService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupExecuteTrajectoryAction'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupGetPlanningSceneService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupKinematicsService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupMoveAction'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupPlanService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupQueryPlannersService'...
[move_group-2] [0m[96mLoading 'move_group/MoveGroupStateValidationService'...
[move_group-2] [0m[92m
[move_group-2] You can start planning now!
[move_group-2] 
[evaluate.py-11] [1;33m[Wrn] [ServerConfig.cc:900] [0m[1;33mIGN_GAZEBO_SERVER_CONFIG_PATH[0m[1;33m set but no file found,[0m[1;33m no plugins loaded[0m
[evaluate.py-11] [INFO] [1725963733.491623441] [ignition_ros_control]: [ign_ros2_control] Fixed joint [robot_summit_xl_base_footprint_joint] (Entity=56)] is skipped
[evaluate.py-11] [INFO] [1725963733.492362502] [ignition_ros_control]: [ign_ros2_control] Fixed joint [robot_j2s7s300_joint_base] (Entity=57)] is skipped
[evaluate.py-11] [INFO] [1725963733.492389132] [ignition_ros_control]: [ign_ros2_control] Fixed joint [robot_j2s7s300_joint_end_effector] (Entity=65)] is skipped
[evaluate.py-11] [INFO] [1725963733.497948457] [ignition_ros_control]: connected to service!! robot_state_publisher asking for robot_description
[evaluate.py-11] [INFO] [1725963733.498695297] [ignition_ros_control]: Received URDF from param server
[evaluate.py-11] [INFO] [1725963733.509063585] [ignition_ros_control]: Loading joint: robot_summit_xl_front_left_wheel_joint
[evaluate.py-11] [INFO] [1725963733.509094306] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509107986] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509120596] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509135296] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509147236] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509177146] [ignition_ros_control]: Loading joint: robot_summit_xl_back_left_wheel_joint
[evaluate.py-11] [INFO] [1725963733.509191106] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509202006] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509212846] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509224086] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509234956] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509259146] [ignition_ros_control]: Loading joint: robot_summit_xl_front_right_wheel_joint
[evaluate.py-11] [INFO] [1725963733.509271896] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509282436] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509293136] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509304566] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509315926] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509346156] [ignition_ros_control]: Loading joint: robot_summit_xl_back_right_wheel_joint
[evaluate.py-11] [INFO] [1725963733.509358276] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509369006] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509379756] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509390826] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509401296] [ignition_ros_control]: 		 effort
[evaluate.py-11] [WARN] [1725963733.509501846] [ignition_ros_control]: On init...
[evaluate.py-11] [INFO] [1725963733.509560256] [ignition_ros_control]: System Successfully configured!
[evaluate.py-11] [INFO] [1725963733.509713016] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_1
[evaluate.py-11] [INFO] [1725963733.509736526] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509750656] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509766616] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509779436] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509791846] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509804016] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509831096] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_2
[evaluate.py-11] [INFO] [1725963733.509846366] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509858576] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509870646] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509882416] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509894296] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.509906816] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509932896] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_3
[evaluate.py-11] [INFO] [1725963733.509945626] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.509956926] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.509968246] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.509979336] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.509990556] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510002266] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510028636] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_4
[evaluate.py-11] [INFO] [1725963733.510041786] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510081876] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510096506] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510108216] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510119636] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510131056] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510156326] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_5
[evaluate.py-11] [INFO] [1725963733.510173186] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510184356] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510195366] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510207156] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510233496] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510246906] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510272557] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_6
[evaluate.py-11] [INFO] [1725963733.510285527] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510296977] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510308197] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510319477] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510330347] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510341807] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510367687] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_7
[evaluate.py-11] [INFO] [1725963733.510381967] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510393367] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510412327] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510424207] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510435717] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510446817] [ignition_ros_control]: 		 effort
[evaluate.py-11] [WARN] [1725963733.510464227] [ignition_ros_control]: On init...
[evaluate.py-11] [INFO] [1725963733.510482447] [ignition_ros_control]: System Successfully configured!
[evaluate.py-11] [INFO] [1725963733.510637287] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_1
[evaluate.py-11] [INFO] [1725963733.510659047] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510671067] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510682717] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510693957] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510705737] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510717427] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510742757] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_2
[evaluate.py-11] [INFO] [1725963733.510756257] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510767637] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510779347] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510790237] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510801687] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510813367] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510841457] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_3
[evaluate.py-11] [INFO] [1725963733.510854427] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510865117] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510876207] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510887147] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510898537] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510909707] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.510934987] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_tip_1
[evaluate.py-11] [INFO] [1725963733.510948287] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.510959557] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.510970617] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.510981797] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.510992987] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.511016837] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_tip_2
[evaluate.py-11] [INFO] [1725963733.511030287] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.511041337] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.511052437] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.511063827] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.511087007] [ignition_ros_control]: 		 effort
[evaluate.py-11] [INFO] [1725963733.511113167] [ignition_ros_control]: Loading joint: robot_j2s7s300_joint_finger_tip_3
[evaluate.py-11] [INFO] [1725963733.511127597] [ignition_ros_control]: 	Command:
[evaluate.py-11] [INFO] [1725963733.511138707] [ignition_ros_control]: 	State:
[evaluate.py-11] [INFO] [1725963733.511149987] [ignition_ros_control]: 		 position
[evaluate.py-11] [INFO] [1725963733.511161417] [ignition_ros_control]: 		 velocity
[evaluate.py-11] [INFO] [1725963733.511173877] [ignition_ros_control]: 		 effort
[evaluate.py-11] [WARN] [1725963733.511186017] [ignition_ros_control]: On init...
[evaluate.py-11] [INFO] [1725963733.511201377] [ignition_ros_control]: System Successfully configured!
[evaluate.py-11] [INFO] [1725963733.511224357] [ignition_ros_control]: Loading controller_manager
[evaluate.py-11] [WARN] [1725963733.587902691] [ignition_ros_control]:  Desired controller update period (0.004 s) is slower than the gazebo simulation period (0 s).
[evaluate.py-11] [1;33mWarning [GenericJoint.hpp:1480][0m [GenericJoint::setRestPosition] Value of _q0 [0], is out of the limit range [0.820305, 5.46288] for index [0] of Joint [Joint].
[evaluate.py-11] [1;33mWarning [GenericJoint.hpp:1480][0m [GenericJoint::setRestPosition] Value of _q0 [0], is out of the limit range [0.523599, 5.75959] for index [0] of Joint [Joint].
[evaluate.py-11] [1;33mWarning [GenericJoint.hpp:1480][0m [GenericJoint::setRestPosition] Value of _q0 [0], is out of the limit range [1.13446, 5.14872] for index [0] of Joint [Joint].
[evaluate.py-11] [INFO] [1725963733.667109957] [gripper_trajectory_controller]: Command interfaces are [effort] and and state interfaces are [position velocity].
[evaluate.py-11] [INFO] [1725963733.670463350] [gripper_trajectory_controller]: Controller state will be published at 50.00 Hz.
[evaluate.py-11] [INFO] [1725963733.673391603] [gripper_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[evaluate.py-11] [INFO] [1725963733.685162083] [joint_state_broadcaster]: 'joints' or 'interfaces' parameter is empty. All available state interfaces will be published
[evaluate.py-11] [WARN] [1725963735.034800948] [drl_grasping_0]: Action server 'joint_trajectory_controller/follow_joint_trajectory' is not yet available. Better luck next time!
[evaluate.py-11] [INFO] [1725963735.036274640] [drl_grasping_0]: Inserting camera into the environment...
[evaluate.py-11] [INFO] [1725963735.756909842] [parameter_bridge_depth_camera_points]: Creating IGN->ROS Bridge: [/depth_camera/points (ignition.msgs.PointCloudPacked) -> /depth_camera/points (sensor_msgs/msg/PointCloud2)] (Lazy 0)
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD135: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD135: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD134: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD134: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD133: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD133: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD132: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD132: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD131: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD131: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD130: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD130: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD129: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD129: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD128: Permission denied
[evaluate.py-11] 
[evaluate.py-11] libEGL warning: failed to open /dev/dri/renderD128: Permission denied
[evaluate.py-11] 
[evaluate.py-11] [INFO] [1725963740.237971098] [drl_grasping_0]: Inserting invisible plane below the terrain into the environment...
[evaluate.py-11] [INFO] [1725963740.876686515] [drl_grasping_0]: Inserting invisible planes around the terrain into the environment...
[evaluate.py-11] [WARN] [1725963742.715783364] [drl_grasping_0]: Action server 'joint_trajectory_controller/follow_joint_trajectory' is not yet available. Better luck next time!
[evaluate.py-11] [INFO] [1725963743.185197360] [joint_trajectory_controller]: Command interfaces are [effort] and and state interfaces are [position velocity].
[evaluate.py-11] [INFO] [1725963743.187679793] [joint_trajectory_controller]: Controller state will be published at 50.00 Hz.
[evaluate.py-11] [INFO] [1725963743.189876634] [joint_trajectory_controller]: Action status changes will be monitored at 20.00 Hz.
[INFO] [spawner-5]: process has finished cleanly [pid 2998788]
[INFO] [spawner-6]: process has finished cleanly [pid 2998793]
[INFO] [spawner-4]: process has finished cleanly [pid 2998786]
[evaluate.py-11] [INFO] [1725963745.565053891] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.574732299] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.583548077] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.594739766] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.606144186] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.613811602] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.623202740] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.631663228] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.646104349] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.658136570] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.666850237] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.672685842] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.678805287] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.684999943] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.690395317] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.696493092] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.701669146] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.707854122] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.713233536] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.719067421] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.724256766] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.730370341] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.735807396] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.741333750] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.746590935] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.752358419] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.758241474] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.765770871] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.772332566] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.778222011] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.784619657] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.790561892] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.795738066] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.801287611] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.807062505] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.812693430] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.818584365] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.823033329] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.844188837] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.851148593] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.856146338] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.861503902] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.866749826] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.872710851] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.878035416] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.883922651] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.889279605] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.896072001] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.901581146] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963745.908309442] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [WARN] [1725963745.914317597] [drl_grasping_0]: Objects could not be spawned without any overlapping. The workspace might be too crowded!
[evaluate.py-11] [INFO] [1725963746.170673803] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963746.170778434] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963746.226122470] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963746.227851772] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963747.026491289] [drl_grasping_0]: [Curriculum] An object is now closer than the required distance of 0.1
[evaluate.py-11] [INFO] [1725963747.117610766] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963747.118381486] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963747.315116413] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [INFO] [1725963747.927412233] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963747.928182783] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963748.678958511] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963748.682669754] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963748.777925365] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963748.778826535] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963749.636304824] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963749.641527058] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963749.681410633] [drl_grasping_0]: [Curriculum] Touched objects: ['rock1']
[evaluate.py-11] [INFO] [1725963749.766223835] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963749.766278035] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963750.615065957] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963750.622022783] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963750.682670305] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963750.683434625] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963750.718851395] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963750.721363067] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963751.406511221] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963751.413446347] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963751.485101088] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963751.485152768] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963751.542330137] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963751.543060727] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963752.162277715] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963752.170092922] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963752.220330075] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963752.220383645] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963752.226974381] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963752.230008124] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963752.290674235] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963752.290719425] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963752.958057584] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963752.974135508] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963753.091377428] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963753.091429888] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963753.222260400] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963753.686512627] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963753.687293958] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963753.689594970] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963753.691962682] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963753.768004716] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963753.770557458] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963753.814984457] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963753.815051937] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963754.472607699] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963754.480814636] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963754.639667312] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963754.640415622] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963754.786729507] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963755.220809019] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963755.223605651] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963755.286979895] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963755.287031335] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963755.322239146] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963755.322279266] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963755.918695586] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963755.920116977] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963756.081249426] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963756.081318716] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963756.229373883] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963756.693656011] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963756.695453052] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963756.806378567] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963756.806444967] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963757.456649686] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963757.460165709] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963757.584753416] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963757.584810046] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963758.215680618] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963758.218745510] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963758.314652123] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963758.315417513] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963759.177592635] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963759.179350236] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963759.196360351] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963759.196951101] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963759.223567784] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963759.224103275] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963759.977326752] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963759.981468776] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963760.065760619] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963760.065814589] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963760.103754782] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963760.103796372] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963760.760182997] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963760.770364996] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963760.827205765] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963760.827960295] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963760.836544413] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963760.842511748] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963760.866536528] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963760.867027049] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963761.518640821] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963761.523148855] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963761.593628386] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963761.594439826] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963761.795602150] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963762.403375094] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963762.407409527] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963762.412531332] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963762.412673792] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963762.495135973] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963762.495923064] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963763.299859698] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963763.304567062] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963763.424879916] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963763.424936616] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963764.212043527] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963764.213464138] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963764.321127621] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963764.321177181] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963765.078802557] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963765.079833148] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963765.194290238] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963765.198457491] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963766.031385863] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963766.033224084] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963766.123683863] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963766.124456653] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963767.113480891] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963767.117036374] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963767.165470396] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963767.166184137] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963767.206432012] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963767.206974392] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963768.074246885] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963768.078039849] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963768.198037143] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963768.198084913] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963768.424850840] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963769.124423868] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963769.125629240] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963769.238671478] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963769.239473879] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963770.188666755] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963770.193290259] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963770.287552961] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963770.287606651] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963771.136546591] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963771.140424585] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963771.270833908] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963771.271570238] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963772.111529251] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963772.120884189] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963772.211694849] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963772.211759709] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963773.064828154] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963773.065575115] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963773.162286619] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963773.163047770] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963774.063481887] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963774.068901872] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963774.203354460] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963774.203411080] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963774.994900452] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963774.999568346] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963775.072939361] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963775.073677021] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963775.865909456] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963775.869543629] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963775.947790038] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963775.948891088] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963776.757508858] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963776.760741471] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963776.785744652] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963776.785801982] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963776.847778297] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963776.848924148] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963777.575190305] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963777.583071832] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963777.704845349] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963777.705583900] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963777.922305620] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963778.509962477] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963778.514296050] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963778.642318503] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963778.643076634] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963779.359936894] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963779.371341584] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963779.429936406] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963779.429983436] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963780.140060411] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963780.210179113] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963780.212348165] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963780.216488378] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963780.217140489] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963780.286707210] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963780.287537191] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963781.075342465] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963781.076101166] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963781.982577965] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963781.982629525] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963782.757259289] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963782.757892600] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963782.821724856] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963782.822469927] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963783.600245964] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963783.603415627] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963783.761139137] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963783.761889567] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963784.542075647] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963784.543677169] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963784.628527064] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963784.629308465] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963785.325514681] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963785.352599845] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963785.357596729] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963785.359914481] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963785.360628242] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963785.428982122] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963785.429837263] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963786.282659839] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963786.282710589] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963787.140143190] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963787.140192570] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963787.927606539] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963787.951445910] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963787.957506595] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963787.959634087] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963787.959938547] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963788.018999620] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963788.021386542] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963788.876299962] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963788.877036583] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963789.653173953] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963789.654079893] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963789.696606321] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963789.697184882] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963790.494787342] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963790.502490949] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963790.668145267] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963790.668200287] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963790.849827998] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963791.357643951] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963791.362666695] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963791.477040617] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963791.477136747] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963792.080381355] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963792.096653960] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963792.186437020] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963792.186492780] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963792.927293631] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963792.931603585] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963793.031587494] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963793.032313855] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963793.685892889] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963793.689976112] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963793.795332937] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963793.796088857] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963794.443130736] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963794.448689821] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963794.450334072] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963794.453050035] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963794.550522932] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963794.551266292] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963795.454917071] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963795.454964971] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963796.351951885] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963796.365055567] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963796.460391372] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963796.461133892] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963797.255775125] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963797.259503158] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963797.367527155] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963797.368260886] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963798.340612609] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963798.349189486] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963798.458640684] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963798.458692334] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963799.363458828] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963799.366497990] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963799.499140259] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963799.499939430] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963800.452880027] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963800.455187629] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963800.568980762] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963800.569740282] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963801.598681009] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963801.600906491] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963801.738545745] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963801.738604915] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963802.650651708] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963802.666677882] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963802.716399817] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963802.718451879] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963803.601174975] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963803.628777030] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963803.686527462] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963803.687129273] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963804.534286778] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963804.538355502] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963804.706598614] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963804.707356925] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963805.497182819] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963805.513855904] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963805.597786530] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963805.598599600] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963806.432804546] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963806.437082979] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963806.493081140] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963806.493132380] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963806.533054446] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963806.533696167] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963807.359211115] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963807.362384918] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963807.467976014] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963807.468757284] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963807.697490641] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963808.280997661] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963808.282483492] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963808.430656447] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963808.431426567] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963809.062138719] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963809.063679971] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963809.166192034] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963809.166944245] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963809.815849474] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963809.818464977] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963809.914553684] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963809.914602814] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963810.718805355] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963810.721749518] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963810.771643273] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963810.772384364] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963810.812409580] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963810.812979111] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963811.549439511] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963811.553614715] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963811.661348432] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963811.662086573] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963811.698744656] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963811.698785567] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963812.313621016] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963812.319275162] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963812.392333438] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963812.393060369] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963812.403767928] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963812.405915340] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963812.436826119] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963812.439341321] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963813.116971769] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963813.124079215] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963813.217071800] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963813.219050921] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963813.227116969] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963813.235465946] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963813.260013389] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963813.260047399] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963813.908011190] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963813.911912413] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963814.043531483] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963814.044640764] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963814.183903532] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963814.659140255] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963814.659845136] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963814.662868749] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963814.684347368] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963814.705255697] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963814.705302037] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963814.748236867] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963814.748280877] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963815.431059900] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963815.434115903] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963815.563994682] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963815.564045712] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963815.739214162] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963816.215457427] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963816.215717277] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963816.378135136] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963816.378940517] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963817.093500530] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963817.108406544] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963817.185174814] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963817.186458116] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963817.917398634] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963817.920367297] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963817.970699964] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963817.971419264] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963818.015142644] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963818.015744315] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963818.723266963] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963818.726450836] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963818.874609472] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963818.874658912] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963819.076123876] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963819.614570951] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963819.617283773] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963819.666902828] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963819.667626149] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963819.713610432] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963819.714513102] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963820.343102919] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963820.347030023] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963820.456713684] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963820.457453254] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963820.503856687] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963820.504456367] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963821.295750174] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963821.299357187] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963821.436971924] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963821.437725155] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963821.650569370] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963822.206038331] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963822.207779743] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963822.211463646] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963822.219088403] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963822.336912371] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963822.337655442] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963823.123403585] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963823.123776426] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963823.267842808] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963823.267900878] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963823.889315811] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963823.891766793] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963823.980409934] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963823.980458844] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963824.676854686] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963824.680677840] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963824.766556619] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963824.767322630] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963825.410813003] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963825.415598028] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963825.544628497] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963825.544677547] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963826.030661395] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963826.169847044] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963826.171077125] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963826.173392527] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963826.174244737] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963826.242596581] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963826.242652161] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963827.034500252] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963827.035911244] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963827.980505137] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963827.980557167] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963829.173672271] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963829.177993945] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963829.262962093] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963829.263012424] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963830.469276361] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963830.471185073] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963830.595797648] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963830.596562059] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963831.569329372] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963831.579282511] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963831.678696903] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963831.678750033] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963832.440065320] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963832.532157016] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963832.534563348] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963832.536073009] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963832.538258671] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963832.633460740] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963832.634200501] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963833.589400748] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963833.590189519] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963834.517183561] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963834.518088492] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963834.532828475] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963834.616034653] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963835.049521306] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963835.057262414] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963835.062819219] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963836.284907237] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.293786905] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.301994973] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.308356769] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.316495507] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.323944404] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.331610840] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.338906657] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.349230827] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.356812014] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.364831631] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.371103607] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.378779765] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.387565843] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.395466710] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.402372526] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.409465543] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.417147300] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.427481950] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.434615257] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.443431105] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.451390052] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.460258181] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.468629858] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.476731936] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.483732232] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.493511042] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.504809242] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.524119270] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.540689285] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.550661505] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.559096563] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.568318161] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.575922668] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.584397956] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.593208965] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.601360052] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.608683329] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.618801358] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.627928307] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.635866774] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.643896432] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.653154370] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.661862938] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.670750977] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.677954504] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.687867823] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.695703830] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.705889580] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [INFO] [1725963836.713350077] [drl_grasping_0]: Objects overlapping, trying new positions
[evaluate.py-11] [WARN] [1725963836.721581724] [drl_grasping_0]: Objects could not be spawned without any overlapping. The workspace might be too crowded!
[evaluate.py-11] [INFO] [1725963836.766717276] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963836.766780326] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963837.558672865] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963837.559426736] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963838.283624892] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963838.283674082] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963838.974957867] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963838.978403271] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963839.013488184] [drl_grasping_0]: [Curriculum] An object is now closer than the required distance of 0.1
[evaluate.py-11] [INFO] [1725963839.016274146] [drl_grasping_0]: [Curriculum] Touched objects: ['rock7']
[evaluate.py-11] [INFO] [1725963839.088424793] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963839.089212174] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963839.841225197] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963839.843122769] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963839.870110934] [drl_grasping_0]: [Curriculum] Grasped objects: ['rock7']
[evaluate.py-11] [INFO] [1725963839.975812843] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963839.976608014] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963840.645403970] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963840.650785805] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963840.774882171] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963840.775928102] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963841.387867265] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963841.399257126] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963841.462251274] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963841.462297814] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963842.091499474] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963842.094653417] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963842.198630775] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963842.198680675] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963842.847078202] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963842.847227472] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963842.931076621] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963842.931810901] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963843.558349420] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963843.562750954] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963843.662310937] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963843.662362737] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963844.452212679] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963844.455202502] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963844.545367006] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963844.545430846] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963845.293607499] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963845.318727403] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963845.321726545] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963845.323141527] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963845.325094969] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963845.392586502] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963845.392640612] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963846.274836112] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963846.275604292] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963847.144707700] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963847.145489871] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963847.866226930] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963847.871642085] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963847.959875868] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963847.960625358] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963848.594783936] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963848.597603229] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963848.652303000] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963848.652352431] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963848.706905032] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963848.706955622] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963849.329067429] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963849.340405219] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963849.447101800] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963849.447845431] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963849.602103066] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963850.069398917] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963850.071514759] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963850.141602305] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963850.141650066] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963850.733913105] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963850.736519387] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963850.812409899] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963850.813162679] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963851.426934829] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963851.429672082] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963851.482337052] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963851.482387252] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963851.526555513] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963851.526600663] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963852.126113690] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963852.130730455] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963852.245895453] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963852.246662624] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963852.403748573] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963852.898989451] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963852.902479654] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963852.999576616] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963852.999630267] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963853.043997488] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963853.044040418] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963853.656632858] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963853.659676281] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963853.732086810] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963853.732832681] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963853.754460281] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963853.755115652] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963854.365278670] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963854.371683836] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963854.540079915] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963854.540816176] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963854.705955712] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963855.210290651] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963855.211796062] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963855.220119620] [drl_grasping_0]: Action 'gripper_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963855.220285430] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963855.292310948] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963855.293058129] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963855.866835193] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963855.993886324] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963855.994563195] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963856.002229712] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963856.003413903] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963856.055201612] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963856.055295792] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963856.878441713] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963856.879184734] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963857.491598846] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963857.587137157] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963857.588638958] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963857.663047559] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963857.663107739] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963858.567013058] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963858.567061698] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963859.361302534] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963859.361355804] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963859.409598640] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963859.409641580] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963860.083404691] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963860.084314152] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963860.165962009] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963860.166704370] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963860.378622732] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963860.915804684] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963860.940567617] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963861.009222613] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963861.009956914] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963861.812102969] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963861.813498830] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963861.877788131] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963861.878554482] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963862.605369195] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963862.607847858] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963862.707180982] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963862.708021873] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963863.505061764] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963863.507060456] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963863.548875146] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963863.548924676] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963863.585630661] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963863.586252962] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963864.314996658] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963864.318093461] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963864.466443562] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963864.467212743] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963864.671323649] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963865.226247879] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963865.227981011] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963865.298038628] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963865.298801878] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963865.997763638] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963866.002510252] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963866.106927042] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963866.107679423] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963866.789470065] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963866.790876117] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963866.883319215] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963866.884112466] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963867.559805664] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963867.591580254] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963867.708996596] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963867.709045546] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963868.362654813] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963868.368347699] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963868.457059974] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963868.457809624] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963869.122725112] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963869.129829049] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963869.219032444] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963869.219775395] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963869.910229288] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963869.918772236] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963870.016948761] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963870.017706561] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963870.694942022] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963870.696349163] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963870.795626459] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963870.796389249] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963871.488074604] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963871.492084278] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963871.564381328] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963871.565120939] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963872.226810875] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963872.234461112] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963872.310590836] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963872.311686117] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963873.002508122] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963873.017686026] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963873.033871782] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963873.033908182] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963873.724662427] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963873.724829547] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963873.832324791] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963873.833057632] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963874.515586849] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963874.516787511] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963874.603216404] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963874.603265704] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963875.247947835] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963875.251286189] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963875.353803597] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963875.354552148] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963875.985968147] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963875.987593999] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963876.091282369] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963876.092076570] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963876.805337709] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963876.807686501] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963876.913219373] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963876.913268453] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963877.553983992] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963877.555948774] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963877.614772471] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963877.615565652] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963878.271700906] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963878.289475253] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963878.390970601] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963878.391017141] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963879.071113309] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963879.074435702] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963879.272560964] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963879.272615574] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963879.975498364] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963879.978048917] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963880.066985323] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963880.067702734] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963880.767547952] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963880.771205905] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963880.857349969] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963880.858131140] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963881.641953579] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963881.643250461] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963881.661299918] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963881.661343028] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963881.730612876] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963881.731294016] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963882.545849766] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963882.565630896] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963882.642663620] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963882.642716611] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963882.835147827] [gripper_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963883.477473140] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963883.477582361] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963883.570208031] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963883.570943561] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963884.384806032] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963884.386557464] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963884.485271400] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963884.486019000] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963885.234674568] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963885.236433110] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963885.356548817] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963885.356599547] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963886.052134114] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963886.053911755] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963886.152981582] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963886.155778745] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963886.819908501] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963886.833440044] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963886.835089056] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963886.838148439] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963886.840355551] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963886.929035767] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963886.929092117] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963887.745806023] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963887.746580174] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963888.542700639] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963888.543979211] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963889.222780493] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963889.223500694] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963889.314715543] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963889.315480044] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963889.975870488] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963889.977667840] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963890.061038661] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963890.061770932] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963890.737941133] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963890.739985004] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963890.847144739] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963890.847194989] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963891.515808582] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963891.519335976] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963891.623192967] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963891.623244617] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963892.341073649] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963892.349813338] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963892.435551742] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963892.436332282] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963893.083396276] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963893.094342466] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963893.230734330] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963893.231689241] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963893.882165297] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963893.885079120] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963893.974046457] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963893.974095857] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963894.665810175] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963894.669189129] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963894.755917784] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963894.755969374] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963895.475071849] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963895.478719752] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963895.546881389] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963895.549134731] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963896.229013348] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963896.231331470] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963896.328139225] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963896.328869996] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963897.040429514] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963897.075625209] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963897.197448408] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963897.197502419] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963898.003888571] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963898.013583380] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963898.122717407] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963898.123454808] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963898.866874209] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963898.869320751] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963898.983943434] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963898.983994444] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963899.751419929] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963899.751830969] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963899.817057313] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963899.817116703] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963900.633854827] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963900.639482602] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963900.730624162] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963900.731392223] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963901.554455874] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963901.557138056] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963901.656327514] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963901.657081335] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963902.555701430] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963902.557224972] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963902.640939814] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963902.640993164] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963903.560918712] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963903.562833184] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963903.681248111] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963903.681989851] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963904.591177379] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963904.595653453] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963904.699033665] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963904.699761426] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963905.494489641] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963905.497077643] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963905.588710674] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963905.590528816] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963906.309459446] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963906.321951999] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963906.381201148] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963906.381990679] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963907.187523385] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963907.190975189] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963907.292717559] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963907.293464930] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963908.108427866] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963908.108778307] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963908.194561792] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963908.194613292] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963908.902084863] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963908.909716290] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963908.965663405] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963908.965709365] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963909.659658513] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963909.660757055] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963909.761006534] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963909.762000705] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963910.511921598] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963910.534563601] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963910.614620800] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963910.615363711] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963911.311911593] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963911.316715427] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963911.398966828] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963911.399749009] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963912.055652701] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963912.058472633] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963912.155290830] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963912.155340920] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963912.893851294] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963912.898452458] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963912.979620279] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963912.979675109] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963913.673750318] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963913.678350983] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963913.754552109] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963913.755352509] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963914.422115173] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963914.425671287] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963914.527869608] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963914.527921608] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963915.216036823] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963915.216735014] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963915.276908604] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963915.276960344] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963916.033757837] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963916.035513339] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963916.186885409] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963916.187622640] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963916.905604986] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963916.908843289] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963917.038590749] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963917.038653139] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963917.818758776] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963917.822254070] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963917.967181535] [joint_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963917.967979195] [joint_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [ERROR] [1725963917.980871328] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963917.983355730] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [INFO] [1725963917.984865632] [gripper_trajectory_controller]: Received new action goal
[evaluate.py-11] [INFO] [1725963917.985311432] [gripper_trajectory_controller]: Accepted new action goal
[evaluate.py-11] [INFO] [1725963918.538262584] [joint_trajectory_controller]: Goal reached, success!
[evaluate.py-11] [ERROR] [1725963918.559916806] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] [ERROR] [1725963918.569580715] [drl_grasping_0]: Action 'joint_trajectory_controller/follow_joint_trajectory' was unsuccessful: 5.
[evaluate.py-11] Loading latest experiment, id=1
[evaluate.py-11] INFO: Making new env: GraspPlanetary-PointNet-Gazebo-v0 ({'robot_model': 'lunalab_summit_xl_gen'})
[evaluate.py-11] INFO: Making new env: GraspPlanetary-PointNet-v0 ({'physics_rate': 500.0, 'real_time_factor': 3.4028234663852886e+38, 'world': '/root/ws/install/share/drl_grasping/worlds/lunar.sdf', 'robot_model': 'lunalab_summit_xl_gen', 'camera_type': 'depth_camera', 'camera_width': 128, 'camera_height': 128, 'physics_engine': 0})
[evaluate.py-11] Initialised PointCloudCnnFeaturesExtractor with 653136 parameters
[evaluate.py-11] Initialised PointCloudCnnFeaturesExtractor with 653136 parameters
[evaluate.py-11] Evaluating for 2 episodes with a deterministic policy.
[evaluate.py-11] --- Episode 1/2
[evaluate.py-11] Episode Reward: -1.00
[evaluate.py-11] Episode Length 100
[evaluate.py-11] Success?: False
[evaluate.py-11] Current success rate: 0.00%
[evaluate.py-11] --- Episode 2/2
[evaluate.py-11] Episode Reward: 63.00
[evaluate.py-11] Episode Length 100
[evaluate.py-11] Success?: False
[evaluate.py-11] Current success rate: 0.00%
[evaluate.py-11] Success rate: 0.00%
[evaluate.py-11] Mean reward: 31.00 +/- 32.00
[evaluate.py-11] Mean episode length: 100.00 +/- 0.00
[evaluate.py-11] DONE.
[evaluate.py-11]    
[evaluate.py-11] Exception in thread Thread-1:
[evaluate.py-11] Traceback (most recent call last):
[evaluate.py-11]   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
[evaluate.py-11] free(): invalid next size (fast)
[evaluate.py-11] Received interrupt signal SIGABRT
[evaluate.py-11] Found signal callback
[ERROR] [evaluate.py-11]: process has died [pid 2998820, exit code -11, cmd '/root/ws/install/lib/drl_grasping/evaluate.py --env GraspPlanetary-PointNet-Gazebo-v0 --env-kwargs robot_model:"lunalab_summit_xl_gen" --env-kwargs robot_model:"lunalab_summit_xl_gen" --algo tqc --seed 77 --num-threads -1 --n-episodes 2 --log-folder /root/drl_grasping_training/train/GraspPlanetary-PointNet-Gazebo-v0/logs --exp-id 0 --load-best false --load-checkpoint 250000 --stochastic false --reward-log /root/drl_grasping_training/evaluate/GraspPlanetary-PointNet-Gazebo-v0 --norm-reward False --no-render true --verbose 1 --ros-args --log-level error --ros-args --params-file /tmp/launch_params__hcms4bf'].
slurmstepd-i6-gpu-1: error: *** JOB 7248 ON i6-gpu-1 CANCELLED AT 2024-09-10T10:26:12 ***
INFO:    Cleanup error: while unmounting /var/lib/apptainer/mnt/session/underlay/opt directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libzmq.so.5.2.2 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libz.so.1.2.11 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libwind.so.0.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libutil-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libtinyxml2.so.6.2.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libtinyxml.so.2.6.2 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libtasn1.so.6.6.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libssl.so.1.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libssh.so.4.8.4 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libspdlog.so.1.5.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libsodium.so.23.3.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/librtmp.so.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/librt-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libroken.so.18.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libresolv-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libqhull_r.so.7.2.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libpthread-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libpsl.so.5.3.2 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libprotobuf.so.17.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libpgm-5.2.so.0.0.122 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libnss_files-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libnorm.so.1.5.8 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libnghttp2.so.14.19.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libnettle.so.7.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libminizip.so.1.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libm-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/liblzma.so.5.2.4 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.12 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.12 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libkrb5.so.3.3 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libkeyutils.so.1.8 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libignition-transport11.so.11.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libignition-msgs8.so.8.4.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libignition-math6.so.6.10.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libidn2.so.0.3.6 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libhogweed.so.5.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libgnutls.so.30.27.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libgmp.so.10.4.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libgcc_s.so.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libfcl.so.0.5.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libexpat.so.1.6.11 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libelf-0.176.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libdw-0.176.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libdl-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libcurl.so.4.6.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libcrypt.so.1.1.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libcom_err.so.2.1 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libccd.so.2.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libc-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libbz2.so.1.0.4 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libbrotlidec.so.1.0.7 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1.0.7 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.71.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.71.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.71.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libboost_chrono.so.1.71.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libassimp.so.5.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/libacl.so.1.1.2253 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/ld-2.31.so directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/x86_64-linux-gnu/gconv directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/python3.8 directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/lib/locale directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/underlay/usr/local directory: device or resource busy, while unmounting /var/lib/apptainer/mnt/session/final directory: device or resource busy
